server:
  port: 8881

spring:
  application:
    name: config-client
  cloud:
    config:
#      uri: http://localhost:8888/
      profile: dev
      label: master
      discovery:
        service-id:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/